# Generated by Django 5.0.4 on 2024-05-08 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ChatHub", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["-created_at"]},
        ),
    ]
